/* chk.h */
/*
 * Copyright (c) 2022 Stephen D. Adams <stephen@sdadams.org>
 * Copyright (c) 2026 David Uhden Collado <daviduhden@gmail.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*
 * This file belongs to emuxfs, The Enhanced Multiplexed File System (see NOTICE.md).  The original
 * copyright notice above is preserved; see NOTICE.md for provenance.
 *
 * The concrete checksum state is defined here rather than in an opaque
 * generated byte blob.  The original design cast a weakly aligned
 * "uint8_t priv[N]" object to a struct demanding stronger alignment, which is
 * undefined behaviour.  Defining the concrete type in the header keeps the
 * size and alignment correct and removes the type punning entirely.  Only the
 * modules that actually allocate a struct emuxfs_chk include this header;
 * every other module sees the forward declaration in emuxfs.h.
 */

#ifndef _CHK_H_
#define _CHK_H_

#include <md5.h>
#include <sha1.h>
#include <stdint.h>
#include <unistd.h>
#include <zlib.h>

#include "emuxfs.h"

struct emuxfs_chk_alg {
	enum emuxfs_chk_alg_type type;
	size_t chk_size;
	void (*chk_init)(struct emuxfs_chk *, struct emuxfs_chk_alg *);
	void (*chk_update)(struct emuxfs_chk *, const uint8_t *, size_t);
	void (*chk_final)(uint8_t *, struct emuxfs_chk *);
	const char *name;
};

union emuxfs_chk_impl {
	uLong		ulong;
	MD5_CTX		md5_ctx;
	SHA1_CTX	sha1_ctx;
};

struct emuxfs_chk {
	struct emuxfs_chk_alg	*alg;
	union emuxfs_chk_impl	 impl;
};

#endif /* _CHK_H_ */
